source .env 

DOCKER_IMAGE_TAG=$(git rev-parse --abbrev-ref HEAD)

echo $DOCKER_USERNAME/$DOCKER_REPOSITORY:$DOCKER_IMAGE_TAG

docker build -t $DOCKER_USERNAME/$DOCKER_REPOSITORY:$DOCKER_IMAGE_TAG .
docker run --env-file .env -p 5000:5000 -it $DOCKER_USERNAME/$DOCKER_REPOSITORY:$DOCKER_IMAGE_TAG