source .env 

DOCKER_IMAGE_TAG=$(git rev-parse --abbrev-ref HEAD)

echo $DOCKER_USERNAME/$DOCKER_REGISTRY:$DOCKER_IMAGE_TAG

docker build -t $DOCKER_USERNAME/$DOCKER_REGISTRY:$DOCKER_IMAGE_TAG .
docker run --env-file .env -p 443:5000 -it $DOCKER_USERNAME/$DOCKER_REGISTRY:$DOCKER_IMAGE_TAG
# docker run -p 5000:5000 -e DEV_DB_HOST=$DEV_DB_HOST -e DEV_DB_USERNAME=$DEV_DB_USERNAME -e DEV_DB_PASSWORD=$DEV_DB_PASSWORD -it sasidharan/storeapi:main